### ISSUE TITLE
The Safari version is wrong for me

### ISSUE THREAD

**Issue by julienetie** [julienetie/detect-browser#1]
"My Safari version : 17.4.1 (19618.1.15.11.14)
The script return: 605.1.15" - @NatachaH

From:
https://gist.github.com/julienetie/af1c6cb289047cbcbdfd4b7e2f9b1492?permalink_comment_id=5012484#gistcomment-5012484

**Comment by julienetie** [comment]
I added a fix 
@NatachaH are you able to re-test?

**Comment by NatachaH** [comment]
Yes it works, thank you !

Quick question, is it normal in Firefox and Chrome to not have the full version number (e.g.: Firefox version 124.0.2 return 124.0) ? Not a huge probleme because I still can detect the version, but just for my own knowledge :D

**Comment by julienetie** [comment]
Thanks for confirming. Good question, I can't confirm just yet but I was actually looking into this for Safari and they do normalize the versions in their UAs like your example. I'll add a ticket for that.
